pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - "status-success=Test typescript-action / test"
    actions:
      merge:
        method: merge
